name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15.2
        restart: always
        environment:
          POSTGRES_USER: gitguesser
          POSTGRES_PASSWORD: gitguesser
          POSTGRES_DB: gitguesser_db
        ports:
          - 5432:5432


    steps:
      - uses: actions/checkout@v2
      - name: Build and run containers
        run: docker-compose -f compose.yaml up -d --build
        volumes:
          - ./backend:/backend
          - ./backend/tests:/tests
      - name: Run tests
        run: docker-compose -f compose.yaml exec backend pytest
      - name: Stop containers
        run: docker-compose -f compose.yaml down
